"""empty message

Revision ID: 4f709a6a226
Revises: e7dac3f048
Create Date: 2015-09-23 08:28:53.343464

"""

# revision identifiers, used by Alembic.
revision = '4f709a6a226'
down_revision = 'e7dac3f048'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'result_all')
    op.drop_column('users', 'result_no_stop_words')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
